import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class PdfExport {
  /// Exports the given title + content as a shareable PDF.
  static Future<void> export({
    required String title,
    required String content,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return [
            pw.Text(
              title,
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              'Generated by JagX AI',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey600,
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Text(
              content,
              style: const pw.TextStyle(
                fontSize: 11,
                lineSpacing: 1.4,
              ),
            ),
          ];
        },
      ),
    );

    final bytes = await doc.save();
    final dir = await getTemporaryDirectory();
    final filename = '${_sanitize(title)}.pdf';
    final file = File('${dir.path}/$filename');
    await file.writeAsBytes(bytes);

    await Share.shareXFiles(
      [XFile(file.path)],
      text: title,
    );
  }

  static String _sanitize(String input) {
    final cleaned = input
        .replaceAll(RegExp(r'[^a-zA-Z0-9\s-]'), '')
        .trim()
        .replaceAll(RegExp(r'\s+'), '_')
        .toLowerCase();
    if (cleaned.isEmpty) return 'jagx_ai';
    return cleaned.length > 40 ? cleaned.substring(0, 40) : cleaned;
  }
}
